### ISSUE TITLE
write a demo web which can fetch data from IPFS

### ISSUE THREAD

**Issue by Zhang-Tianxu** [VOKA-AI/.github#9]

**Comment by Zhang-Tianxu** [comment]
Implement a demo website base on [IPFS javascript API](https://github.com/ipfs/js-ipfs) which can fetch data from IPFS network, prepare for playing live stream from IPFS.

**Comment by zhch0633** [comment]
seen the first task, and me to

**Comment by Zhang-Tianxu** [comment]
Related TODO in 飞书：[TODO 3](https://dg00n02a0d.feishu.cn/base/bascnlpeDesIxwWUhVbtmsE2SUc?field=fldyiX2s4I&record=recF48lyuh&table=tblpB2NJYlCNrE9U&view=vewjsusI8J)
